services:
  web:
    build:
      context: microblog_api
      dockerfile: ../Dockerfile
    restart: unless-stopped
    ports:
      - "3040:3000"
    volumes:
      - data:/app/pb_data

volumes:
  data:
