tap "aws/tap"
tap "homebrew/bundle"
tap "oven-sh/bun"
# tap "sdkman/tap"

# C/C++ tools
brew "cmake"

# Java tools
# brew "sdkman-cli"

# JavaScript
brew "nvm"
brew "bun"

# Version control
brew "gh"
brew "mercurial"

# Compression Tools
brew "zlib"
# brew "pigz"

# cURL but not Curly
brew "wget"

# Ruby
brew "openssl@3"
brew "rbenv"

# Deployment software
brew "aws/tap/copilot-cli"

# Editors and terminals
brew "neovim"
brew "tmux"
brew "tmuxinator"

# Casks:

# Editors and terminals
cask "alacritty"
cask "wezterm"
cask "emacs"
cask "vscodium"

# Fancy mouse movment
cask "linearmouse"

# Monitor control
cask "MonitorControl"
