name: serverless

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3040:3000"
    volumes:
      - data:/app/pb_data
      - data:/app/pb_migrations

volumes:
  data:
  migrations:
