# based on:
#.  doceker install: https://docs.docker.com/engine/install/debian/#install-using-the-repository
#.  compose install: https://github.com/docker/compose#where-to-get-docker-compose
#
# usage: ansible-playbook -i hosts-file docker/docker-install.yaml
#
# contents of hosts-file:
# [docker]
# 192.168.0.101
---
- hosts: docker
  tasks:
      # accommodate of suite rename in debian buster from stable to oldstable
      - name: Allow Release Info change
        lineinfile:
            path: /etc/apt/apt.conf.d/99releaseinfochange
            state: present
            create: yes
            line: Acquire::AllowReleaseInfoChange::Suite "true";

      - name: Update apt cache - valid time so it is not marked by ansible by each execution
        apt:
            update_cache: yes
            cache_valid_time: 86400
      - name: install utils
        apt:
            name:
                - ca-certificates
                - curl
                - gnupg
                - lsb-release

      - name: add apt key for docker repo
        apt_key:
            keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
            url: https://download.docker.com/linux/debian/gpg

      - name: Add specified repository into sources list
        ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/debian bookworm stable
            state: present

      - name: Update apt cache - valid time so it is not marked by ansible by each execution
        apt:
            update_cache: yes
            cache_valid_time: 86400

      - name: install docker
        apt:
            name:
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-compose-plugin
                - docker-buildx-plugin
