#!/bin/bash

if [[ ! -e $HOME/Sherman/notes/public ]]
then
    git clone git@github.com:Caleb-T-Owens/public-notes.git public
fi

if [[ ! -e $HOME/Sherman/notes/private ]]
then
    git clone git@github.com:Caleb-T-Owens/private-notes.git private
fi

sync() {
    export GIT_AUTHOR_NAME="Robo-committer"
    export GIT_AUTHOR_EMAIL="robo-committer@intherain.cloud"
    export GIT_COMMITTER_NAME="Robo-committer"
    export GIT_COMMITTER_EMAIL="robo-committer@intherain.cloud"

    local dir=$1
    pushd $dir

    local status_entries=$(git status --porcelain | wc -l)
    if [[ $status_entries -ne 0 ]]
    then
        git add .
        git commit -m "Updated notes"
        echo "Committed updated notes"
    else
        echo "No notes changed"
    fi

    git fetch

    local upstream=$(git rev-parse origin/master)
    local merge_base=$(git merge-base origin/master HEAD)

    if [[ $upstream != $merge_base ]]
    then
        if git merge origin/master
        then
            echo "Merged upstream changes successful"
        else
            git add .
            git commit -m "Merge notes w/conflict"
            echo "Merged upstream changes with committed conflicts"
        fi
    else
        echo "No upstream changes to integrate"
    fi

    local head=$(git rev-parse HEAD)

    if [[ $upstream != $head ]]
    then
        git push
    else
        echo "No changes to push"
    fi

    popd

    unset GIT_AUTHOR_NAME
    unset GIT_AUTHOR_EMAIL
    unset GIT_COMMITTER_NAME
    unset GIT_COMMITTER_EMAIL
}

sync $HOME/Sherman/notes/public
sync $HOME/Sherman/notes/private