[colors.bright]
black = "0x57606a"
blue = "0x218bff"
cyan = "0x1b7c83"
green = "0x0969da"
magenta = "0x8250df"
red = "0x8a4600"
white = "0x6e7781"
yellow = "0x633c01"

[colors.cursor]
cursor = "0x24292f"
text = "0xffffff"

[colors.normal]
black = "0x24292f"
blue = "0x0969da"
cyan = "0x1b7c83"
green = "0x0550ae"
magenta = "0x8250df"
red = "0xb35900"
white = "0x6e7781"
yellow = "0x4d2d00"

[colors.primary]
background = "0xffffff"
foreground = "0x1b1f24"

# # Default colors
# [colors.primary]
# background = '#1d2021'
# foreground = '#d4be98'
# 
# # Normal colors
# [colors.normal]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
# 
# # Bright colors (same as normal colors)
# [colors.bright]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'

[font]
size = 26.0

[font.normal]
family = "CommitMonoDotted"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[window]
dynamic_padding = true
