CONFIGS = macos/brew macos/nvm macos/linearmouse macos/sdkman macos/wezterm macos/ghostty macos/vscodium macos/zsh shared/git shared/neovim shared/bun shared/rustup shared/patc shared/claude-code macos/sdkman
ACTIONS = shared/action-clone-projects shared/action-memory-bootstrap

.PHONY: all
all:
	for config in $(CONFIGS); do \
		(cd $$config && $(MAKE)); \
	done
	for action in $(ACTIONS); do \
		(cd $$action && $(MAKE)); \
	done

.PHONY: unlock
unlock:
	rm $(wildcard */make-lock */*/make-lock */*/*/make-lock)
