CONFIGS = shared/git shared/neovim shared/rustup debian/bash debian/dmenu debian/dwm debian/xorg debian/xinit-config debian/st shared/ripgrep shared/patc shared/claude-code
ACTIONS = shared/action-clone-projects shared/action-sync-buildables debian/action-aptfile-sync

.PHONY: all
all:
	for config in $(CONFIGS); do \
		(cd $$config && $(MAKE)); \
	done
	for action in $(ACTIONS); do \
		(cd $$action && $(MAKE)); \
	done

.PHONY: unlock
unlock:
	rm $(wildcard */make-lock */*/make-lock */*/*/make-lock)

