CONFIGS = shared/git shared/neovim shared/rustup
ACTIONS = # shared/action-clone-projects

.PHONY: all
all:
	for config in $(CONFIGS); do \
		(cd $$config && $(MAKE)); \
	done
	for action in $(ACTIONS); do \
		(cd $$action && $(MAKE)); \
	done

.PHONY: unlock
unlock:
	rm $(wildcard */make-lock */*/make-lock */*/*/make-lock)

